web/TestPropiedades/routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('inmuebles.index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('inmuebles','\App\Http\Controllers\InmueblesController');

web/TestPropiedades/app/Models/Inmueble.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inmueble extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'key',
        'd_tipo_trans',
        'd_tipo_inmu',
    ];

    public function caracteristicas()
    {
        return $this->hasMany('App\Models\InmueblesCaracte');
    }
    public function ubicacion()
    {
        return $this->hasOne('App\Models\InmueblesUbicacione');
    }
}

web/TestPropiedades/app/Http/Controllers/InmueblesController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\Request;
use Auth;
use App\Models\Inmueble;
use App\Models\InmueblesCaracte;
use App\Models\InmueblesIMagene;
use App\Models\InmueblesUbicacione;

class InmueblesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $inmuebles=Inmueble::all();
        return view('Inmueble.index',compact('inmuebles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Inmueble.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $this->validate($request,[
        'nombre'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:10',
        'tipo_trans'=>'required',
        'tipo_inmueble'=>'required',
        'precio'=>'required|Numeric',
        'description'=>'required|max:1500|min:10',
        'estado'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'municipio'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'colonia'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'calle'=>'required|max:255|min:5',
        'numeroDireccion'=>'required|alpha_num|max:15|min:1',
        'lat'=>'required',
        'lng'=>'required']);
      $inmueble = new Inmueble;
      $inmueble->name = $request->nombre;

      $inmueble->d_tipo_trans = $request->tipo_trans;
      $inmueble->d_tipo_inmu = $request->tipo_inmueble;
      $inmueble->price = $request->precio;
      $inmueble->key = 'PCOM-XXX/';
      $inmueble->description = $request->description;
      $inmueble->user_id = Auth::id();
      $inmueble->save();
      $inmueble->key = 'PCOM-XXX/'.$inmueble->id;
      $inmueble->save();

      $caracteristicas = $request->caracteristicas;
      foreach($caracteristicas as $caracteristica){

        $inmueblesCaracte = new InmueblesCaracte;
        $inmueblesCaracte->inmueble_id = $inmueble->id;
        $inmueblesCaracte->caracteristicas = $caracteristica;
        $inmueblesCaracte->save();
       }


      $inmueblesUbicacione = new InmueblesUbicacione;
      $inmueblesUbicacione->estado = $request->estado;
      $inmueblesUbicacione->municipio = $request->municipio;
      $inmueblesUbicacione->colonia = $request->colonia;
      $inmueblesUbicacione->calle = $request->calle;
      $inmueblesUbicacione->numero = $request->numeroDireccion;
      $inmueblesUbicacione->lat = $request->lat;
      $inmueblesUbicacione->lng = $request->lng;
      $inmueblesUbicacione->inmueble_id =  $inmueble->id;
      $inmueblesUbicacione->save();

      for ($i = 1; $i <= 6; $i++) {
        $inmueblesIMagene = new InmueblesIMagene;
        $inmueblesIMagene->ubicacion_id= $inmueblesUbicacione->id;
        $inmueblesIMagene->url = 'https://picsum.photos/200/200?random='.rand(1,1000000);
        $inmueblesIMagene->save();
      }


      return redirect()->route('inmuebles.index')->with('success','Registro Creado satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $inmueble=Inmueble::find($id);
      return  view('Inmueble.show',compact('inmueble'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $inmueble=Inmueble::find($id);

      return view('Inmueble.edit',compact('inmueble'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request,[
        'nombre'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:10',
        'tipo_trans'=>'required',
        'tipo_inmueble'=>'required',
        'precio'=>'required|Numeric',
        'description'=>'required|max:1500|min:10',
        'estado'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'municipio'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'colonia'=>'required|regex:/^[\pL\s\-]+$/u|max:255|min:3',
        'calle'=>'required|max:255|min:5|',
        'numeroDireccion'=>'required|alpha_num|max:15|min:1',
        'lat'=>'required',
        'lng'=>'required']);

        $inmueble =  Inmueble::find($id);
        $inmueble->name = $request->nombre;

        $inmueble->d_tipo_trans = $request->tipo_trans;
        $inmueble->d_tipo_inmu = $request->tipo_inmueble;
        $inmueble->price = $request->precio;
        $inmueble->key = 'PCOM-XXX/'.$inmueble->id;
        $inmueble->description = $request->description;
        $inmueble->user_id = Auth::id();
        $inmueble->save();

        $inmueblesUbicacione = InmueblesUbicacione::find($inmueble->id);
        $inmueblesUbicacione->estado = $request->estado;
        $inmueblesUbicacione->municipio = $request->municipio;
        $inmueblesUbicacione->colonia = $request->colonia;
        $inmueblesUbicacione->calle = $request->calle;
        $inmueblesUbicacione->numero = $request->numeroDireccion;
        $inmueblesUbicacione->lat = $request->lat;
        $inmueblesUbicacione->lng = $request->lng;
        $inmueblesUbicacione->inmueble_id =  $inmueble->id;
        $inmueblesUbicacione->save();

        $model=InmueblesCaracte::where('inmueble_id',$inmueble->id)->delete();

        $caracteristicas = $request->caracteristicas;
        foreach($caracteristicas as $caracteristica){

          $inmueblesCaracte = new InmueblesCaracte;
          $inmueblesCaracte->inmueble_id = $inmueble->id;
          $inmueblesCaracte->caracteristicas = $caracteristica;
          $inmueblesCaracte->save();
         }

        return redirect()->route('inmuebles.index')->with('success','Registro modificado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Inmueble::find($id)->delete();
      return redirect()->route('inmuebles.index')->with('success','Registro eliminado satisfactoriamente');
    }
}

web/TestPropiedades/resources/views/Inmueble/create.blade.php
@extends('layouts.app')

@section('content')
@if (count($errors) > 0)
<div class="alert alert-danger">
	<strong>Error!</strong> Revise los campos obligatorios.<br><br>
	<ul>
		@foreach ($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
</div>
@endif
@if(Session::has('success'))
<div class="alert alert-info">
	{{Session::get('success')}}
</div>
@endif
<div class="container text-right">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Creación de nuevo inmueble</div>
                <div class="card-body">
                  <form method="POST" action="{{ route('inmuebles.store') }}"  role="form">
							             {{ csrf_field() }}
                    <div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Nombre</label>
                      <div class="col-md-10">
                        <input type="input" class="form-control" id="inputNombre" placeholder="Nombre" name="nombre">
                      </div>
                    </div>
                    <div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Descripción</label>
                      <div class="col-md-10">
                        <textarea class="form-control" rows="5" id="description" name="description"></textarea>
                      </div>
                    </div>
                    <div class="form-group row mb-2">
                      <label for="select" class="col-md-2 col-form-label">Tipo de transacción</label>
                      <div class="col-md-2">
                        <select class="form-select" aria-label="Default select example" name="tipo_trans">
                          <option value="venta">Venta</option>
                          <option value="renta">Renta</option>
                        </select>
                      </div>
                      <label for="select" class="col-md-2 col-form-label">Tipo de inmueble</label>
                      <div class="col-md-2">
                        <select class="form-select" aria-label="Default select example" name="tipo_inmueble">
                          <option value="casa">Casa</option>
                          <option value="departamento">Departamento</option>
                          <option value="terreno">Terreno</option>
                          <option value="otros">Otros</option>
                        </select>
                      </div>
                      <label for="select" class="col-md-2 col-form-label">Precio en MXN</label>
                      <div class="col-md-2">
                          <input type="input" class="form-control" id="inputPrecio" placeholder="Precio"  name="precio">
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label for="inputNombre" class="col-md-2 col-form-label">caracteristicas</label>
                      <div class="col-md-10 text-left">
												<select class="form-select js-example-basic-multiple" name="caracteristicas[]" multiple="multiple">
													<option value="clima">Clima</option>
													<option value="estacionamiento" >Estacionamiento</option>
													<option value="patio">Patio</option>
													<option value="Shampoo">Shampoo</option>
													<option value="Agua caliente">Agua caliente</option>
													<option value="Ganchos">Ganchos</option>
													<option value="Ropa de cama">Ropa de cama</option>
													<option value="TV">TV</option>
													<option value="Calefacción">Calefacción</option>
													<option value="Botiquín">Botiquín</option>
													<option value="Wifi">Wifi</option>
													<option value="Refrigerador">Refrigerador</option>
													<option value="Microondas">Microondas</option>
													<option value="Cafetera">Cafetera</option>
													<option value="Barbacoa">Barbacoa</option>
													<option value="Jacuzzi">Jacuzzi</option>
													<option value="Cocina">Cocina</option>
													<option value="Lavadora">Lavadora</option>
												</select>
                      </div>
                    </div>
										<div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Estado</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputEstado" placeholder="Estado" name="estado">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Delegación o municipio</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputEstado" placeholder="Delegación o municipio" name="municipio">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Colonia</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputColonia" placeholder="Colonia" name="colonia">
                      </div>
                    </div>
										<div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Calle</label>
                      <div class="col-md-6">
                        <input type="input" class="form-control" id="inputCalle" placeholder="Calle" name="calle">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Numero</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputNumero" placeholder="Numero" name="numeroDireccion">
                      </div>
                    </div>

										<div class="form-group">
										    <label for="address_address">Dirección</label>
										    <input type="text" id="address-input" name="address_address" class="form-control map-input">
										    <input type="hidden" name="lng" id="address-latitude" />
										    <input type="hidden" name="lat" id="address-longitude" />
										</div>
										<div id="address-map-container" style="width:100%;height:400px; ">
										    <div style="width: 100%; height: 100%" id="address-map"></div>
										</div>
										<div class="form-group row mb-2">
                      <input type="submit"  value="Guardar" class="btn btn-info col-md-3">
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection
@section('scripts')
    @parent
		<script src="/js/mapInput.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize" async defer></script>
		<script type="text/javascript">
		$(document).ready(function() {
		    $('.js-example-basic-multiple').select2();
		});
		</script>
@stop

web/TestPropiedades/resources/views/Inmueble/edit.blade.php
@extends('layouts.app')

@section('content')
@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
<div class="container text-right">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Creación de nuevo inmueble</div>
                <div class="card-body">
                	<form method="POST" action="{{ route('inmuebles.update',$inmueble->id) }}"  role="form">
											@method('PUT')
							             {{ csrf_field() }}
                    <div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Nombre</label>
                      <div class="col-md-10">
                        <input type="input" class="form-control" id="inputNombre" placeholder="Nombre" name="nombre" value="{{$inmueble->name}}">
                      </div>
                    </div>
                    <div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Descripción</label>
                      <div class="col-md-10">
                        <textarea class="form-control" rows="5" id="description" name="description" >{{$inmueble->description}}</textarea>
                      </div>
                    </div>
                    <div class="form-group row mb-2">
                      <label for="select" class="col-md-2 col-form-label">Tipo de transacción</label>
                      <div class="col-md-2">
                        <select class="form-select" aria-label="Default select example" name="tipo_trans">
                          <option value="venta" {{ $inmueble->d_tipo_trans == 'venta' ? 'selected' : '' }}>Venta</option>
                          <option value="renta" {{ $inmueble->d_tipo_trans == 'renta' ? 'selected' : '' }}>Renta</option>
                        </select>
                      </div>
                      <label for="select" class="col-md-2 col-form-label">Tipo de inmueble</label>
                      <div class="col-md-2">
                        <select class="form-select" aria-label="Default select example" name="tipo_inmueble">
                          <option value="casa" {{ $inmueble->d_tipo_inmu == 'casa' ? 'selected' : '' }}>Casa</option>
                          <option value="departamento" {{ $inmueble->d_tipo_inmu == 'departamento' ? 'selected' : '' }}>Departamento</option>
                          <option value="terreno" {{ $inmueble->d_tipo_inmu == 'terreno' ? 'selected' : '' }}>Terreno</option>
                          <option value="otros" {{ $inmueble->d_tipo_inmu == 'otros' ? 'selected' : '' }}>Otros</option>
                        </select>
                      </div>
                      <label for="select" class="col-md-2 col-form-label">Precio en MXN</label>
                      <div class="col-md-2">
                          <input type="input" class="form-control" id="inputPrecio" placeholder="Precio"  name="precio"  value="{{$inmueble->price}}" >
                      </div>
                    </div>
										<div class="form-group row mb-4">
                      <label for="inputNombre" class="col-md-2 col-form-label">caracteristicas</label>
                      <div class="col-md-10 text-left">
												<select class="form-select js-example-basic-multiple" name="caracteristicas[]" multiple="multiple">
													<option value="clima">Clima</option>
													<option value="estacionamiento" >Estacionamiento</option>
													<option value="patio">Patio</option>
													<option value="Shampoo">Shampoo</option>
													<option value="Agua caliente">Agua caliente</option>
													<option value="Ganchos">Ganchos</option>
													<option value="Ropa de cama">Ropa de cama</option>
													<option value="TV">TV</option>
													<option value="Calefacción">Calefacción</option>
													<option value="Botiquín">Botiquín</option>
													<option value="Wifi">Wifi</option>
													<option value="Refrigerador">Refrigerador</option>
													<option value="Microondas">Microondas</option>
													<option value="Cafetera">Cafetera</option>
													<option value="Barbacoa">Barbacoa</option>
													<option value="Jacuzzi">Jacuzzi</option>
													<option value="Cocina">Cocina</option>
													<option value="Lavadora">Lavadora</option>
												</select>
                      </div>
                    </div>
										<div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Estado</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputEstado" placeholder="Estado" name="estado" value="{{$inmueble->ubicacion->estado}}">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Delegación o municipio</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputEstado" placeholder="Delegación o municipio" name="municipio" value="{{$inmueble->ubicacion->municipio}}">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Colonia</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputColonia" placeholder="Colonia" name="colonia" value="{{$inmueble->ubicacion->colonia}}">
                      </div>
                    </div>
										<div class="form-group row mb-2">
                      <label for="inputNombre" class="col-md-2 col-form-label">Calle</label>
                      <div class="col-md-6">
                        <input type="input" class="form-control" id="inputCalle" placeholder="Calle" name="calle" value="{{$inmueble->ubicacion->calle}}">
                      </div>
                      <label for="inputNombre" class="col-md-2 col-form-label">Numero</label>
                      <div class="col-md-2">
                        <input type="input" class="form-control" id="inputNumero" placeholder="Numero" name="numeroDireccion" value="{{$inmueble->ubicacion->numero}}">
                      </div>
                    </div>
										<div class="form-group">
										    <label for="address_address">Dirección</label>
										    <input type="text" id="address-input" name="address_address" class="form-control map-input">
										    <input type="hidden" name="lng" id="address-latitude"  value="{{$inmueble->ubicacion->lng}}"/>
										    <input type="hidden" name="lat" id="address-longitude" value="{{$inmueble->ubicacion->lat}}"/>
										</div>
										<div id="address-map-container" style="width:100%;height:400px; ">
										    <div style="width: 100%; height: 100%" id="address-map"></div>
										</div>
										<div class="form-group row mb-2">
                      <input type="submit"  value="Guardar" class="btn btn-info col-md-3">
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
    @parent
		<script src="/js/mapInput.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize" async defer></script>
		<script type="text/javascript">
		$(document).ready(function() {
		    $('.js-example-basic-multiple').select2();

				 var datas = {!! json_encode($inmueble->caracteristicas, JSON_HEX_TAG) !!};
				var caracteristicas = [];
				datas.forEach(data => caracteristicas.push(data.caracteristicas))
				setTimeout(() => {
					console.log(caracteristicas)
					$('.js-example-basic-multiple').val(caracteristicas);
					$('.js-example-basic-multiple').trigger('change');
				}, 500);


		});
		</script>
@stop

web/TestPropiedades/resources/views/Inmueble/index.blade.php
@extends('layouts.app')

@section('content')

@if (count($errors) > 0)
<div class="alert alert-danger">
	<strong>Error!</strong> Revise los campos obligatorios.<br><br>
	<ul>
		@foreach ($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
</div>
@endif
@if(Session::has('success'))
<div class="alert alert-info">
	{{Session::get('success')}}
</div>
@endif
<div class="container">
  <div class="form-group">

      <input type="hidden" name="lng" id="address-latitude"/>
      <input type="hidden" name="lat" id="address-longitude"/>
  </div>
  <div id="address-map-container" style="width:100%;height:400px; ">
      <div style="width: 100%; height: 100%" id="address-map"></div>
  </div>
  <div class="row">
    @foreach($inmuebles as $inmueble)
		<div class="col-md-4">
			<div class="card p-4 m-2" >
				<div class="card-body">
					<p>Clave: {{$inmueble->key}}</p>
					<p>Dirección: {{$inmueble->ubicacion->calle}} #{{$inmueble->ubicacion->numero}}</p>
				</div>
	      <img class="card-img-top" src="{{$inmueble->ubicacion->imagenes->first()->url}}" alt="Card image cap">
	      <div class="card-body">
	        <div class="row">
	            <p class="card-text col-md-4 text-secondary"><a style="color:gray" href="{{ url("/inmuebles/{$inmueble->id}") }}"><i class="fas fa-eye fa-4x "></i></a>
	            @auth
	            <p class="card-text col-md-4 text-secondary"><a style="color:gray" class="text-second" href="{{ url("/inmuebles/{$inmueble->id}/edit") }}"><i class="fas fa-pen fa-4x "> </i></a>
	            <form method="POST" action="{{ route('inmuebles.destroy',$inmueble->id) }}"  role="form" class="col-md-4 text-secondary">
	                   {{csrf_field()}}
	                   <input name="_method" type="hidden" value="DELETE">
	                   <button class="btn btn-primary-outline" style="color:gray" type="submit"><i class="fas fa-trash-alt fa-4x"></i></button>
	            </form>
	            @endauth
	        </div>
	      </div>
	    </div>
		</div>

    @endforeach
</div>
@endsection
@section('scripts')
    @parent
		<script type="text/javascript">

		function initialize() {

				const latitude = 19.3545705;
				const longitude = -99.084642;
				 var data = {!! json_encode($inmuebles, JSON_HEX_TAG) !!};
				 console.log(data.length)

				const map = new google.maps.Map(document.getElementById('address-map'), {
						center: {lat: latitude, lng: longitude},
						zoom: 13
				});
				for (var i = 0; i < data.length; i++) {
					console.log(data[i].ubicacion.lat)
					console.log(data[i].ubicacion.lng)

					const marker = new google.maps.Marker({
							map: map,
							position: {lat: data[i].ubicacion.lng, lng: data[i].ubicacion.lat},
					});

					marker.setVisible(true);
				}

			}
		</script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize" async defer></script>

@stop